language: php

php:
  - 5.4

services:
  - memcached
  - redis-server
  - riak

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit -c phpunit.xml